<a href="https://colab.research.google.com/github/dhaferaljaziri/-on-Protecting-Personal-Data-on-the-Interne/blob/main/NumPy_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy --upgrade


In [ ]:
import numpy as np
print(np.__version__)


2.3.2


1. إنشاء مصفوفة

In [ ]:
import numpy as np

# إنشاء مصفوفة 1D
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# إنشاء مصفوفة 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


2. أعداد متسلسلة (arange / linspace)

In [ ]:
# أعداد من 0 إلى 9
a = np.arange(10)
print("arange(10):", a)

# أعداد بين 0 و 1 مقسمة إلى 5 أجزاء
b = np.linspace(0, 1, 5)
print("linspace(0,1,5):", b)


arange(10): [0 1 2 3 4 5 6 7 8 9]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]


3. عمليات رياضية على المصفوفات

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("x + y =", x + y)
print("x * y =", x * y)
print("x dot y =", np.dot(x, y))


x + y = [11 22 33]
x * y = [10 40 90]
x dot y = 140


4. دوال مهمة

In [ ]:
m = np.array([[1, 2], [3, 4]])

print("Transpose:\n", m.T)
print("Sum of all elements:", np.sum(m))
print("Mean of all elements:", np.mean(m))
print("Max element:", np.max(m))


Transpose:
 [[1 3]
 [2 4]]
Sum of all elements: 10
Mean of all elements: 2.5
Max element: 4


5. المصفوفات العشوائية

In [ ]:
# مصفوفة 2x2 أعداد عشوائية بين 0 و 1
rand_arr = np.random.rand(2,2)
print("Random 2x2 array:\n", rand_arr)

# مصفوفة 3x3 من أعداد صحيحة عشوائية بين 0 و 10
rand_int = np.random.randint(0, 10, (3,3))
print("Random integers:\n", rand_int)


Random 2x2 array:
 [[0.70540537 0.9113824 ]
 [0.75640833 0.64612334]]
Random integers:
 [[4 1 8]
 [4 7 5]
 [6 4 2]]
